Sprint 3: add Smart home diagrams using C4
AlbertDavletov/architecture-sprint-3 pull request #1
Opened 2024-12-08 22:31 UTC by AlbertDavletov

- Разбор задания в README.md
- Исходный код диаграм находится в папке docs

2024-12-12 06:27 UTC, dchekushin requested changes

2024-12-12 06:27 UTC, dchekushin commented on README.md
> +![Диаграмма монолитного приложения](./docs/images/smart-home-monolith-c4.png)
1. Стоит выделить мобильное приложение или веб-сайт отдельным контейнером. ПОльзователь взаимодействует с сайтом, который в свою очередь, отправляет запросы в монолит.
3. Подпиши потоки данных, протоколы и технологии взаимодействия (HTTP и т.д.) на стрелках между контейнерами.

2024-12-12 06:27 UTC, dchekushin commented on README.md
> +![C4 — Уровень контейнеров (Containers)](./docs/images/smart-home-containers-c4.png)
Подпиши потоки данных, протоколы и технологии взаимодействия (HTTP и т.д.) на стрелках между контейнерами.
API датчиков должно быть за пределами smart home system, оно же внешняя система.

2024-12-12 06:27 UTC, dchekushin commented on README.md
> +![C4 — Уровень компонентов (Components)](./docs/images/smart-home-components-c4.png)
Здесь все хорошо описано. Я бы добавил контейнеры баз данных и описание стрелок на диаграмму уровня контейнеров. На уровне компонентов детализируется взаимодействие внутри одного выбранного микросервиса.

Таким образом, у нас будет общая схема системы и детализированная схема сервиса, которую можно дополнительно изучить.

2024-12-12 06:27 UTC, dchekushin commented on README.md
> +![C4 — ER диаграмма](./docs/images/smart-home-er.png)
Хорошо описана сущности. Одно небольшое замечание: для атрибута, описывающего статус устройства (включено/выключено), стоит использовать тип данных enum, так как список статусов ограничен.

2024-12-13 06:53 UTC, AlbertDavletov commented on README.md
> +![Диаграмма монолитного приложения](./docs/images/smart-home-monolith-c4.png)
Согласен, поправил. Спасибо за фидбек!

2024-12-13 06:54 UTC, AlbertDavletov commented on README.md
> +![C4 — Уровень контейнеров (Containers)](./docs/images/smart-home-containers-c4.png)
Поправил.

2024-12-13 06:55 UTC, AlbertDavletov commented on README.md
> +![C4 — Уровень компонентов (Components)](./docs/images/smart-home-components-c4.png)
Спасибо. Я более детально описал сервис управление устройствами и взаимодействие между компонентами этого сервиса.

2024-12-13 06:55 UTC, AlbertDavletov commented on README.md
> +![C4 — ER диаграмма](./docs/images/smart-home-er.png)
поправил.

2024-12-13 09:44 UTC, dchekushin approved these changes

2024-12-14 06:56 UTC, merged